name: Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Theos
        uses: Randomblock1/theos-action@v1

      - name: Build Application
        run: make package FINALPACKAGE=1

      - name: Upload IPA
        uses: actions/upload-artifact@v4
        with:
          name: CatExplorer-IPA
          path: packages/*.ipa
