name: Release

on:
  push:
    tags:
      - '*'

permissions:
  contents: write

jobs:
  release:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Theos
        uses: Randomblock1/theos-action@v1

      - name: Build Application
        run: make package FINALPACKAGE=1

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          name: CatExplorer ${{ github.ref_name }}
          generate_release_notes: true
          files: packages/*.ipa
